name: Docker Compose
on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      projectName:
        required: true
        type: string
    secrets:
      host:
        required: true
      username:
        required: true
      key:
        required: true
env:
  # Use docker.io for Docker Hub if empty
  PROJECT_NAME: minesweeper
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        key: ${{ secrets.key }}
        script: |
          mkdir -p /app/${{ inputs.projectName }}
          cd /app/${{ inputs.projectName }}
          # echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          if [ -f docker-compose.yml ]; then docker-compose stop; fi
          curl -H 'Cache-Control: no-cache, no-store' https://raw.githubusercontent.com/${{ inputs.namespace }}/${{ inputs.projectName }}/main/docker-compose.yml -s > docker-compose.yml
          cat docker-compose.yml
          docker-compose pull
          docker-compose up -d
